name: Build and Deploy to CloudHub 2.0 (Sandbox)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # Connected App (Secrets)
      ANYPOINT_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      ANYPOINT_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}

  
      ANYPOINT_ENV: Sandbox
      CH2_TARGET: Shared Space 
      MULE_APP_NAME: usecase-cicd-deploy

      # Sizing
      CH2_REPLICAS: "1"
      CH2_VCORES: "0.1"

      # Runtime
      MULE_VERSION: "4.8.0"
      MULE_JAVA_VERSION: "17"


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build + Deploy to CH2 (publish to Exchange if configured)
        run: |
          mvn -B clean deploy \
            -DmuleDeploy \
            -DskipTests \
            -DskipDeploymentVerification=true \
            -s .maven/settings.xml
