name: Build and Deploy to CloudHub 2.0 (Sandbox)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # Connected App (Secrets)
      ANYPOINT_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      ANYPOINT_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # -----------------------
      # BUILD STEP
      # -----------------------
      - name: Build Mule application
        run: |
          mvn -B clean package \
            -DskipTests \
            -s .maven/settings.xml

      # -----------------------
      # DEPLOY STEP (CH2)
      # -----------------------
      - name: Deploy to CloudHub 2.0 Sandbox
        run: |
          mvn -B deploy \
            -DmuleDeploy \
            -DskipTests \
            -DskipDeploymentVerification=true \
            -s .maven/settings.xml
